; Listing generated by Microsoft (R) Optimizing Compiler Version 19.14.26433.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\andrew.cutler\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
